name: Build and Run Windows Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      VS_YEAR: 2017
      VS_VERSION: 15
      CMAKE_VERSION: 3.21.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build --no-cache `
            --build-arg VS_YEAR=${{ env.VS_YEAR }} `
            --build-arg VS_VERSION=${{ env.VS_VERSION }} `
            --build-arg CMAKE_VERSION=${{ env.CMAKE_VERSION }} `
            -t crossplatformapp-windows-vs2017 `
            -f Dockerfile.windows.vs .

      - name: Run Docker container
        run: |
          docker run --rm crossplatformapp-windows-vs2017