name: Build and Run Docker Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: crossplatformapp-windows
  IMAGE_TAG: latest  # Using 'latest' for simplicity; consider using ${{ github.sha }} for production.

jobs:
  build-and-run:
    name: Build and Run Application in Docker
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile.windows .

      - name: Run Build Script Inside Docker
        run: docker run