name: Docker Build and Run CrossPlatformApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-linux-docker:
    name: Build and Run Docker (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image (Linux)
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            -t crossplatformapp-linux -f Dockerfile . \
            --load

      - name: Move New Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run Docker Container (Linux)
        run: docker run --rm crossplatformapp-linux

  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (Windows)
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers (Windows)
        uses: actions/cache@v3
        with:
          path: C:/tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image (Windows)
        run: |
          docker buildx build `
            --cache-from=type=local,src=C:/tmp/.buildx-cache `
            --cache-to=type=local,dest=C:/tmp/.buildx-cache-new `
            -t crossplatformapp-windows -f Dockerfile.windows . `
            --load

      - name: Move New Cache (Windows)
        run: |
          Remove-Item -Recurse -Force C:/tmp/.buildx-cache
          Rename-Item C:/tmp/.buildx-cache-new C:/tmp/.buildx-cache

      - name: Run Docker Container (Windows)
        run: docker run --rm crossplatformapp-windows
