name: Docker Build and Run on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-linux-docker:
    name: Build and Run Docker (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image (Linux)
        run: |
          docker build --no-cache -t crossplatformapp-linux -f Dockerfile.linux .

      - name: Run Build Script Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -v "${{ github.workspace }}:/workspace" crossplatformapp-linux bash -c "./build.sh"

      - name: Run Application Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -v "${{ github.workspace }}:/workspace" crossplatformapp-linux bash -c "./run.sh"
