name: Docker Build and Run on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_VERSION: 3.21.3
  IMAGE_PREFIX: crossplatformapp-vs
  APP_WORKDIR: C:\app
  SCRIPTS_PATH: C:\scripts\windows
  BUILD_SCRIPT: build.cmd
  RUN_SCRIPT: run.cmd
  DOCKERFILE_PATH: Dockerfile.windows.vs

jobs:
  build-and-run-windows-docker:
    runs-on: windows-latest

    strategy:
      matrix:
        vs_version: [15, 16, 17]
        config: [Debug, Release]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        run: |
          docker build --no-cache `
            --build-arg VS_VERSION=${{ matrix.vs_version }} `
            --build-arg CMAKE_VERSION=$env:CMAKE_VERSION `
            -t $env:IMAGE_TAG `
            -f $env:DOCKERFILE_PATH .

      - name: Run Build Script Inside Docker
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        run: |
          docker run --rm `
            -e CONFIG=${{ matrix.config }} `
            -v "${{ github.workspace }}:$env:APP_WORKDIR" `
            $env:IMAGE_TAG `
            cmd.exe /c "$env:SCRIPTS_PATH\${{ env.BUILD_SCRIPT }} ${{ matrix.config }} ${{ matrix.vs_version }} > $env:APP_WORKDIR\build.log 2>&1"

      - name: Display Build Logs (if failure)
        if: failure()
        run: |
          type C:\app\build.log

      - name: Run Application Inside Docker
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        run: |
          # Execute the compiled application inside the Docker container.
          docker run --rm `
            -e CONFIG=${{ matrix.config }} `
            -v "${{ github.workspace }}:$env:APP_WORKDIR" `
            $env:IMAGE_TAG `
            cmd.exe /c "$env:SCRIPTS_PATH\${{ env.RUN_SCRIPT }}"
