name: Docker Build and Run on Windows Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest

    env:
      DOCKER_IMAGE_NAME: crossplatformapp-windows
      DOCKER_CONTAINER_NAME: crossplatformapp-container
      VS_VERSION: 16

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Host Temp Directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "${{ github.workspace }}\Temp" -Force

      - name: Build Docker Image
        shell: pwsh
        run: |
          docker build --no-cache `
            --build-arg VS_VERSION=$env:VS_VERSION `
            -t $env:DOCKER_IMAGE_NAME `
            -f Dockerfile.windows.vs .

      - name: Run Build Inside Docker
        shell: pwsh
        run: |
          $config = "Release"
          docker run --rm --name $env:DOCKER_CONTAINER_NAME `
            -e CONFIG=$config `
            -e VS_VERSION=$env:VS_VERSION `
            -v "${{ github.workspace }}:C:\app" `
            -v "${{ github.workspace }}\Temp:C:\TEMP" `
            $env:DOCKER_IMAGE_NAME `
            powershell -NoProfile -ExecutionPolicy Bypass -Command `
            "Set-Location 'C:\app\scripts\windows'; .\build.ps1 -CONFIG $config -VS_VERSION $env:VS_VERSION"
          
            
      - name: Extract Build Tools Installation Log
        shell: pwsh
        run: |
          docker create --name extract-log $env:DOCKER_IMAGE_NAME
          docker cp extract-log:C:/TEMP/vs_buildtools_install.log ${{ github.workspace }}/Temp/vs_buildtools_install.log
          docker rm extract-log

      - name: Display Build Tools Installation Log
        shell: pwsh
        run: |
          if (Test-Path "Temp/vs_buildtools_install.log") {
            Write-Host "----- Begin vs_buildtools_install.log -----"
            Get-Content "Temp/vs_buildtools_install.log" | Write-Host
            Write-Host "----- End vs_buildtools_install.log -----"
          } else {
            Write-Host "vs_buildtools_install.log not found."
          }

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vs-buildtools-log
          path: Temp/vs_buildtools_install.log

      - name: Cleanup Docker Resources
        if: always()
        shell: pwsh
        run: |
          docker ps -a -q --filter "name=$env:DOCKER_CONTAINER_NAME" | ForEach-Object { docker rm -f $_ }
