name: Build and Run Docker Image for Visual Studio 2017

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Base Docker Image
      run: |
        docker build --no-cache -t base -f Dockerfile.windows.base .

    - name: Build Docker Image for Visual Studio 2017
      run: |
        docker build --no-cache --build-arg CMAKE_VERSION=3.21.3 -t crossplatformapp-vs2017 -f Dockerfile.windows.vs17 .

    - name: Run Build Script Inside Docker
      run: |
        docker run --rm -e CONFIG=Release -v "${{ github.workspace }}:C:\app" crossplatformapp-vs2017 cmd.exe /c C:\scripts\windows\build.vs17.cmd

    - name: Run Application Inside Docker
      run: |
        docker run --rm -e CONFIG=Release -v "${{ github.workspace }}:C:\app" crossplatformapp-vs2017 cmd.exe /c C:\scripts\windows\run.cmd