name: Docker Build and Run on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        vs_year: [2017]
    env:
      CMAKE_VERSION: 3.21.3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set VS_VERSION
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts/windows/set_vs_version.ps1

      - name: Debug VS_VERSION
        shell: bash
        run: echo "VS_VERSION=${{ env.VS_VERSION }}"

      - name: Build Base Docker Image
        shell: bash
        run: docker build --no-cache -t base -f Dockerfile.windows.base .

      - name: Build Visual Studio Docker Image
        shell: bash
        run: |
          docker build --no-cache \
            --build-arg VS_YEAR=${{ matrix.vs_year }} \
            --build-arg VS_VERSION=${{ env.VS_VERSION }} \
            --build-arg CMAKE_VERSION=${{ env.CMAKE_VERSION }} \
            -t crossplatformapp-windows-vs${{ matrix.vs_year }} \
            -f Dockerfile.windows.vs .

      - name: Debug Environment Inside Docker
        run: |
          & docker run --rm -e CONFIG=${{ matrix.config }} -e VS_YEAR=${{ matrix.vs_year }} -e VS_VERSION=${{ env.VS_VERSION }} `
            -v "${{ github.workspace }}:C:\app" crossplatformapp-windows-vs${{ matrix.vs_year }} cmd.exe /c set

      - name: Run Build Script Inside Docker
        shell: bash
        run: |
          docker run --rm \
            -e CONFIG=${{ matrix.config }} \
            -e VS_YEAR=${{ matrix.vs_year }} \
            -v "${{ github.workspace }}:C:/app" \
            crossplatformapp-windows-vs${{ matrix.vs_year }} \
            powershell -NoProfile -ExecutionPolicy Bypass -File C:/app/scripts/windows/build.ps1
          
      - name: Run Application Inside Docker
        shell: bash
        run: |
          docker run --rm \
            -e CONFIG=${{ matrix.config }} \
            -e VS_YEAR=${{ matrix.vs_year }} \
            -v "${{ github.workspace }}:C:/app" \
            crossplatformapp-windows-vs${{ matrix.vs_year }} \
            powershell -NoProfile -ExecutionPolicy Bypass -File C:/app/scripts/windows/run.ps1
      