name: Docker Build and Run on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_VERSION: 3.21.3
  IMAGE_PREFIX: crossplatformapp-vs
  APP_WORKDIR: C:\app
  SCRIPTS_PATH: C:\scripts\windows
  BUILD_SCRIPT: build.cmd
  RUN_SCRIPT: run.cmd
  DOCKERFILE_PATH: Dockerfile.windows.vs

jobs:
  build-and-run-windows-docker:
    runs-on: windows-latest

    strategy:
      matrix:
        vs_version: [15, 16, 17]
        config: [Debug, Release]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        run: |
          docker build --no-cache `
            --build-arg VS_VERSION=${{ matrix.vs_version }} `
            --build-arg CMAKE_VERSION=$env:CMAKE_VERSION `
            -t $env:IMAGE_TAG `
            -f $env:DOCKERFILE_PATH .

      - name: Debug Mounted Volume
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        shell: pwsh
        run: |
          $hostPath = $env:GITHUB_WORKSPACE -replace '\\', '/'
          $containerPath = 'C:\app'
          Write-Host "Host Path: $hostPath"
          Write-Host "Container Path: $containerPath"
          $mountSpec = "type=bind,source=$hostPath,target=$containerPath"
          Write-Host "Mount Spec: $mountSpec"
          docker run --rm --mount "$mountSpec" $env:IMAGE_TAG cmd.exe /c dir $containerPath

      - name: Run Build Script Inside Docker
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        shell: pwsh
        run: |
          $hostPath = $env:GITHUB_WORKSPACE -replace '\\', '/'
          $containerPath = 'C:\app'
          $mountSpec = "type=bind,source=$hostPath,target=$containerPath"
          docker run --rm `
            -e CONFIG=${{ matrix.config }} `
            -e APP_WORKDIR=$env:APP_WORKDIR `
            -e SCRIPTS_PATH=$env:SCRIPTS_PATH `
            -e BUILD_SCRIPT=$env:BUILD_SCRIPT `
            --mount "$mountSpec" `
            $env:IMAGE_TAG `
            cmd.exe /c "%SCRIPTS_PATH%\%BUILD_SCRIPT% %CONFIG% %VS_VERSION%"

      - name: Display Build Logs (if failure)
        if: failure()
        shell: pwsh
        run: |
          $hostPath = $env:GITHUB_WORKSPACE
          type "$hostPath\build.log"

      - name: Run Application Inside Docker
        env:
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}-${{ matrix.vs_version }}
        shell: pwsh
        run: |
          $hostPath = $env:GITHUB_WORKSPACE -replace '\\', '/'
          $containerPath = 'C:\app'
          $mountSpec = "type=bind,source=$hostPath,target=$containerPath"
          docker run --rm `
            -e CONFIG=${{ matrix.config }} `
            -e APP_WORKDIR=$env:APP_WORKDIR `
            -e SCRIPTS_PATH=$env:SCRIPTS_PATH `
            -e RUN_SCRIPT=$env:RUN_SCRIPT `
            --mount "$mountSpec" `
            $env:IMAGE_TAG `
            cmd.exe /c "%SCRIPTS_PATH%\%RUN_SCRIPT%"