name: Docker Build and Run on Windows (Visual Studio 2022)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image (Windows)
        run: |
          docker build --no-cache --build-arg CMAKE_VERSION=3.21.3 -t crossplatformapp-windows -f Dockerfile.windows.vs22 .

      - name: Run Build Script Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -v "${{ github.workspace }}:C:\app" crossplatformapp-windows cmd.exe /c C:\scripts\windows\build.vs17.cmd

      - name: Run Application Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -v "${{ github.workspace }}:C:\app" crossplatformapp-windows cmd.exe /c C:\scripts\windows\run.cmd
