name: Docker Build and Run on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        vs_year: [2019]
    env:
      CMAKE_VERSION: 3.21.3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set VS_VERSION based on VS_YEAR
        run: |
          chmod +x ./scripts/windows/set_vs_version.sh
          ./scripts/windows/set_vs_version.sh ${{ matrix.vs_year }}

      - name: Debug VS_VERSION
        run: echo "VS_VERSION=${{ env.VS_VERSION }}"

      - name: Set VS_VERSION
        run: |
          if ("${{ matrix.vs_year }}" -eq "2019") {
           echo "VS_VERSION=16" >> $env:GITHUB_ENV
          } elseif ("${{ matrix.vs_year }}" -eq "2022") {
            echo "VS_VERSION=17" >> $env:GITHUB_ENV
          }

      
      - name: Debug VS_VERSION
        run: echo "VS_VERSION=${{ env.VS_VERSION }}"

      - name: Build Base Docker Image
        run: |
          docker build --no-cache -t base -f Dockerfile.windows.base .

      - name: Build Docker Image
        run: |
         echo "VS_VERSION=${{ env.VS_VERSION }}" # Debug the value
         docker build --no-cache \
         --build-arg VS_YEAR=${{ matrix.vs_year }} \
         --build-arg VS_VERSION=${{ env.VS_VERSION }} \
         --build-arg CMAKE_VERSION=${{ env.CMAKE_VERSION }} \
         -t crossplatformapp-windows-vs${{ matrix.vs_year }} \
         -f Dockerfile.windows.vs .
        shell: bash
          
      - name: Build Docker Image
        run: |
          docker build --no-cache --build-arg VS_YEAR=${{ matrix.vs_year }} --build-arg VS_VERSION=${{ env.VS_VERSION }} --build-arg CMAKE_VERSION=${{ env.CMAKE_VERSION }} -t crossplatformapp-windows-vs${{ matrix.vs_year }} -f Dockerfile.windows.vs .

      - name: Run Build Script Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -e VS_YEAR=${{ matrix.vs_year }} -v "${{ github.workspace }}:C:\app" crossplatformapp-windows-vs${{ matrix.vs_year }} cmd.exe /c dir C:\app\scripts\windows && cmd.exe /c C:\app\scripts\windows\build.vs.cmd

      - name: Run Application Inside Docker
        run: |
          docker run --rm -e CONFIG=${{ matrix.config }} -e VS_YEAR=${{ matrix.vs_year }} -v "${{ github.workspace }}:C:\app" crossplatformapp-windows-vs${{ matrix.vs_year }} cmd.exe /c C:\app\scripts\windows\run.cmd
