name: Build and Run Docker Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-windows-docker:
    name: Build and Run Docker (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Dockerfile (Debugging Step)
        run: Get-Content Dockerfile.windows -Raw

      - name: Build Docker Image (Windows)
        run: docker build -t crossplatformapp-windows -f Dockerfile.windows .

      - name: Run Build Script Inside Docker
        run: |
          docker run --rm crossplatformapp-windows cmd.exe /c C:\scripts\build.cmd ${{ matrix.config }}

      - name: Run Application Inside Docker
        run: docker run --rm crossplatformapp-windows
